services:
    flosports.core.service.athlete:
        class: Acme\CoreBundle\Service\AthleteService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@logger"

    flosports.core.service.team:
        class: Acme\CoreBundle\Service\TeamService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@logger"

    flosports.core.form.handler.form_handler:
        class: Acme\CoreBundle\Form\Handler\FormHandler
        arguments:
            - "@form.factory"

    flosports.core.form.type.athlete:
        class: Acme\CoreBundle\Form\Type\AthleteType
        arguments:
            - "@doctrine.orm.default_entity_manager"
        tags:
            - { name: form.type }
